/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "owltex"
include("libs:share-kernel")
findProject(":libs:share-kernel")?.name = "share-kernel"
include("libs:untitled")
findProject(":libs:untitled")?.name = "untitled"
include("apps:order-service")
findProject(":apps:order-service")?.name = "order-service"
include("apps:product-service")
findProject(":apps:product-service")?.name = "product-service"
include("libs:event-bus")
findProject(":libs:event-bus")?.name = "event-bus"
include("libs:database-client")
findProject(":libs:database-client")?.name = "database-client"
